<?php
namespace CollaborativeFilteringDefines;

if ( !defined( 'COLLABORATIVE_FILTERING_PLUGIN' ) )
	exit;

if ( !defined( 'COLLABORATIVE_FILTERING_TABLE_VERSION' ) ) {
	define( 'COLLABORATIVE_FILTERING_TABLE_VERSION', '0.0.0.0.1' );
}

//lib dir
define( 'COLLABORATIVE_FILTERING_LIB_API_DIR', COLLABORATIVE_FILTERING_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "apis" );
define( 'COLLABORATIVE_FILTERING_LIB_MODELS_DIR', COLLABORATIVE_FILTERING_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "models" );
define( 'COLLABORATIVE_FILTERING_LIB_VIEWS_DIR', COLLABORATIVE_FILTERING_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "views" );
define( 'COLLABORATIVE_FILTERING_LIB_MAIL_TEMPLATE_DIR', COLLABORATIVE_FILTERING_LIB_VIEWS_DIR . DIRECTORY_SEPARATOR . "mail_template" );
define( 'COLLABORATIVE_FILTERING_LIB_SERVICES_DIR', COLLABORATIVE_FILTERING_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "services" );
define( 'COLLABORATIVE_FILTERING_LIB_TEST_DIR', COLLABORATIVE_FILTERING_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "test" );
define( 'COLLABORATIVE_FILTERING_LIB_ASSETS_DIR', COLLABORATIVE_FILTERING_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "public" );
define( 'COLLABORATIVE_FILTERING_LIB_CSS_DIR', COLLABORATIVE_FILTERING_LIB_ASSETS_DIR . DIRECTORY_SEPARATOR . "css" );
define( 'COLLABORATIVE_FILTERING_LIB_JS_DIR', COLLABORATIVE_FILTERING_LIB_ASSETS_DIR . DIRECTORY_SEPARATOR . "js" );
define( 'COLLABORATIVE_FILTERING_LIB_IMG_DIR', COLLABORATIVE_FILTERING_LIB_ASSETS_DIR . DIRECTORY_SEPARATOR . "img" );
define( 'COLLABORATIVE_FILTERING_LIB_FONT_DIR', COLLABORATIVE_FILTERING_LIB_ASSETS_DIR . DIRECTORY_SEPARATOR . "fonts" );
define( 'COLLABORATIVE_FILTERING_LIB_PLUGINS_DIR', COLLABORATIVE_FILTERING_LIB_ASSETS_DIR . DIRECTORY_SEPARATOR . "plugins" );
define( 'COLLABORATIVE_FILTERING_LIB_LIBRARY_DIR', COLLABORATIVE_FILTERING_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "library" );
define( 'COLLABORATIVE_FILTERING_LIB_CONFIGS_DIR', COLLABORATIVE_FILTERING_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "configs" );
define( 'COLLABORATIVE_FILTERING_LIB_DIRECT_API_DIR', COLLABORATIVE_FILTERING_LIB_ROOT_DIR . DIRECTORY_SEPARATOR . "direct-api" );

//dir
define( 'COLLABORATIVE_FILTERING_CONTROLLERS_DIR', COLLABORATIVE_FILTERING_ROOT_DIR . DIRECTORY_SEPARATOR . "controllers" );
define( 'COLLABORATIVE_FILTERING_API_DIR', COLLABORATIVE_FILTERING_ROOT_DIR . DIRECTORY_SEPARATOR . "apis" );
define( 'COLLABORATIVE_FILTERING_MODELS_DIR', COLLABORATIVE_FILTERING_ROOT_DIR . DIRECTORY_SEPARATOR . "models" );
define( 'COLLABORATIVE_FILTERING_VIEWS_DIR', COLLABORATIVE_FILTERING_ROOT_DIR . DIRECTORY_SEPARATOR . "views" );
define( 'COLLABORATIVE_FILTERING_MAIL_TEMPLATE_DIR', COLLABORATIVE_FILTERING_VIEWS_DIR . DIRECTORY_SEPARATOR . "mail_template" );
define( 'COLLABORATIVE_FILTERING_SERVICES_DIR', COLLABORATIVE_FILTERING_ROOT_DIR . DIRECTORY_SEPARATOR . "services" );
define( 'COLLABORATIVE_FILTERING_TEST_DIR', COLLABORATIVE_FILTERING_ROOT_DIR . DIRECTORY_SEPARATOR . "test" );
define( 'COLLABORATIVE_FILTERING_ASSETS_DIR', COLLABORATIVE_FILTERING_ROOT_DIR . DIRECTORY_SEPARATOR . "public" );
define( 'COLLABORATIVE_FILTERING_CSS_DIR', COLLABORATIVE_FILTERING_ASSETS_DIR . DIRECTORY_SEPARATOR . "css" );
define( 'COLLABORATIVE_FILTERING_JS_DIR', COLLABORATIVE_FILTERING_ASSETS_DIR . DIRECTORY_SEPARATOR . "js" );
define( 'COLLABORATIVE_FILTERING_IMG_DIR', COLLABORATIVE_FILTERING_ASSETS_DIR . DIRECTORY_SEPARATOR . "img" );
define( 'COLLABORATIVE_FILTERING_FONT_DIR', COLLABORATIVE_FILTERING_ASSETS_DIR . DIRECTORY_SEPARATOR . "fonts" );
define( 'COLLABORATIVE_FILTERING_PLUGINS_DIR', COLLABORATIVE_FILTERING_ASSETS_DIR . DIRECTORY_SEPARATOR . "plugins" );
define( 'COLLABORATIVE_FILTERING_LOG_DIR', COLLABORATIVE_FILTERING_ROOT_DIR . DIRECTORY_SEPARATOR . "logs" );
define( 'COLLABORATIVE_FILTERING_TMP_DIR', COLLABORATIVE_FILTERING_ROOT_DIR . DIRECTORY_SEPARATOR . "tmp" );
define( 'COLLABORATIVE_FILTERING_UPLOAD_DIR', COLLABORATIVE_FILTERING_ROOT_DIR . DIRECTORY_SEPARATOR . "upload" );

//log file
define( 'COLLABORATIVE_FILTERING_LOG_FILE', COLLABORATIVE_FILTERING_LOG_DIR . DIRECTORY_SEPARATOR . "cf.log" );

//update info
define( 'COLLABORATIVE_FILTERING_UPDATE_INFO_FILE_URL', "https://raw.githubusercontent.com/123teru321/CFiltering/master/update.json" );
