<?php
if ( !defined( 'COLLABORATIVE_FILTERING_PLUGIN' ) )
	exit;

define( 'COLLABORATIVE_FILTERING_OUTPUT_LOG', true );
define( 'COLLABORATIVE_FILTERING_SHOW_ERROR', false );
define( 'COLLABORATIVE_FILTERING_NEED_NONCE_CHECK', true );

//db settings
define( 'COLLABORATIVE_FILTERING_TABLE_VERSION', '0.0.0.0.5' );

//cap
define( 'COLLABORATIVE_FILTERING_ADMIN_CAPABILITY', 'manage_options' );

//default settings
define( 'COLLABORATIVE_FILTERING_EXCLUDE_LOGGEDIN_USER', true );
define( 'COLLABORATIVE_FILTERING_USER_EXPIRE', HOUR_IN_SECONDS );
define( 'COLLABORATIVE_FILTERING_UPDATE_COOKIE_EXPIRE', true );
define( 'COLLABORATIVE_FILTERING_SAMPLING_RATE', -1 );
define( 'COLLABORATIVE_FILTERING_CHECK_DATA', true );
define( 'COLLABORATIVE_FILTERING_NONCE_CHECK', COLLABORATIVE_FILTERING_NEED_NONCE_CHECK );
define( 'COLLABORATIVE_FILTERING_CALC_INTERVAL', MINUTE_IN_SECONDS * 10 );
define( 'COLLABORATIVE_FILTERING_CALC_TIMEOUT', MINUTE_IN_SECONDS );
define( 'COLLABORATIVE_FILTERING_CALC_LOG', false );
define( 'COLLABORATIVE_FILTERING_CLEAR_INTERVAL', HOUR_IN_SECONDS );
define( 'COLLABORATIVE_FILTERING_CLEAR_TIMEOUT', MINUTE_IN_SECONDS * 10 );
define( 'COLLABORATIVE_FILTERING_CLEAR_LOG', false );
define( 'COLLABORATIVE_FILTERING_DATA_EXPIRE', DAY_IN_SECONDS );
define( 'COLLABORATIVE_FILTERING_DISPLAY_LOG_NUMBER', 100 );
define( 'COLLABORATIVE_FILTERING_MAX_SAVE_DATA_NUMBER', 20 );
define( 'COLLABORATIVE_FILTERING_MINIFY_JS', true );
define( 'COLLABORATIVE_FILTERING_MINIFY_CSS', true );
define( 'COLLABORATIVE_FILTERING_JACCARD_THRESHOLD', 0 );
define( 'COLLABORATIVE_FILTERING_JACCARD_MIN_NUMBER', 10 );
define( 'COLLABORATIVE_FILTERING_CALCULATE_NUMBER', 10000 );
define( 'COLLABORATIVE_FILTERING_POST_TYPES', 'post' );
define( 'COLLABORATIVE_FILTERING_POST_STATUSES', 'publish' );
define( 'COLLABORATIVE_FILTERING_SHOW_RESULT', true );
define( 'COLLABORATIVE_FILTERING_FRONT_ADMIN_AJAX', false );
define( 'COLLABORATIVE_FILTERING_CHECK_REFERER', true );
define( 'COLLABORATIVE_FILTERING_TEST', true );
define( 'COLLABORATIVE_FILTERING_CONSIDER_PAGE_CACHE', true );
define( 'COLLABORATIVE_FILTERING_URL_SCHEME', 'relative' );
define( 'COLLABORATIVE_FILTERING_UTILIZE_WPP', false );
define( 'COLLABORATIVE_FILTERING_MOD_REWRITE_AJAX_ACCESS', false );
define( 'COLLABORATIVE_FILTERING_HTTP_HOST', '' );
define( 'COLLABORATIVE_FILTERING_SUPPRESS_MESSAGE', false );

//from github
define( 'COLLABORATIVE_FILTERING_CHECK_UPDATE', false );

//default value
define( 'COLLABORATIVE_FILTERING_DEFAULT_SAMPLING_RATE', 1 );

//ajax
define( 'COLLABORATIVE_FILTERING_AJAX_FILE', 'ajax.php' );
define( 'COLLABORATIVE_FILTERING_MOD_REWRITE_AJAX', 'ajax' );
